predictit:
  outputs:
    dev:
      account: 
      database: predictit
      password: dbtPassword123
      role: de_predictit
      schema: dev
      threads: 1
      type: snowflake
      user: dbt_predictit
      warehouse: compute_wh
  target: dev
